alias updt="sudo apt update && sudo apt -y upgrade"
alias inst="sudo apt update && sudo apt install -y"
alias bashedit="vim ~/.bashrc"
alias zshedit="vim ~/.zshrc"
alias aliasedit="vim ~/.bash_aliases"
alias aliases="cat .bashrc | grep "^alias""
alias c="xargs echo -n | xclip -selection clipboard"
alias gsta="git status"
alias gc="git commit -m"
alias gph="git push"
alias gpl="git pull"
alias aliases="grep \"^alias\\s\" $(find ~/.bashrc) && echo && grep \"^alias\\s\" $(find ~/.bash_aliases)"
alias pip="python -m pip"
alias ipy="ipython"

